-- Run this once on your MySQL server to create the database & tables
CREATE DATABASE IF NOT EXISTS auth_verify;
USE auth_verify;

-- Admin users (the ONLY accounts that can log in)
CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL, -- bcrypt hash
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Product codes generated by admin, printed on packaging
CREATE TABLE IF NOT EXISTS product_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  batch_name VARCHAR(100),
  product_name VARCHAR(150),
  status ENUM('unused', 'verified') DEFAULT 'unused',
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
);

-- Log every public verification attempt (genuine or fake)
CREATE TABLE IF NOT EXISTS verification_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  product_code VARCHAR(32) NOT NULL,
  result ENUM('genuine_first_check', 'genuine_already_verified', 'fake') NOT NULL,
  ip_address VARCHAR(45),
  checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Products displayed on the public catalog (managed by admin)
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2),
  image_url VARCHAR(255),  -- relative '/uploads/...' path or external URL
  demo_code VARCHAR(100)
);

